ignore:
  # - 'some/file/in/particular.rb'
  # - 'a/whole/directory/**/*'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'bin/**'
  - 'config/**/*'
  - 'config.ru'
  - 'db/**/*'
  - 'script/**/*'
  - 'spec/rails_helper.rb'
  - 'spec/spec_helper.rb'
  - 'tmp/**/*'
  - 'lib/tasks/**/*'
  - 'vendor/**/*'